### ISSUE TITLE
Why dont you Add CS50x and CS50 Web of Harvard?

### ISSUE THREAD

**Issue by hsumerf** [karlhorky/learn-to-program#38]
CS50x and CS50 Web courses of Harvard are most comprehensive courses till now.CS50 is for introduction to computer sciences and cs50 web for web development complete using python and javascript?

**Comment by karlhorky** [comment]
Can you open a pill request for these? They sound interesting.

**Comment by hsumerf** [comment]
@karlhorky sure ! :)

**Comment by HeyFang** [comment]
umm... you don't really need to, those come under edx... which is already included

**Comment by karlhorky** [comment]
@HeyFang thanks for the note, great that they're included already! Closing...
