### ISSUE TITLE
Build a website to share those awesome resource

### ISSUE THREAD

**Issue by shartoo** [karlhorky/learn-to-program#67]
For a better experence for collect such awesome resource,we build a website to collecting and sharing collections of websites. Just fork and manage like github,welcome to share!

[list of  website resources for programing beginers](https://www.awepage.com/#/home/detail?p=5hJTm-2CNNm)
![0300](https://github.com/karlhorky/learn-to-program/assets/5716282/54df2159-6fa0-4343-ae3e-6a4f157db57d)

[awesome free learning resources for intermediate level code](https://www.awepage.com/#/home/detail?p=3VFKf-2CNNm)

![00345](https://github.com/karlhorky/learn-to-program/assets/5716282/d2d5c807-1a71-4eb7-b379-8a2ca4c4044e)

[ awesome free learning resources for advanced level code](https://www.awepage.com/#/home/detail?p=I9QM-2CNNm)

![0532](https://github.com/karlhorky/learn-to-program/assets/5716282/514cd5e8-9da3-49fb-8fd3-83289699f57a)

**Comment by karlhorky** [comment]
Nice, thanks! I'll close this issue now.
