### ISSUE TITLE
GitHub Learning Lab 404

### ISSUE THREAD

**Issue by vihutr** [karlhorky/learn-to-program#69]
https://lab.github.com/ no longer resolves to the expected web page. Likely now relocated to https://github.com/apps/github-learning-lab as an app?

**Comment by vihutr** [comment]
Website link also leads back to lab.github so maybe just an issue on that end actually?

**Comment by karlhorky** [comment]
I think they've been replaced by [GitHub Skills](https://github.com/skills) - I'll update to that now
